import { Collection, Product, JournalArticle, AtelierContent, SocialLink, FooterColumn, HeroSlide, Project, StoreLocation } from '@/lib/types';
import { img } from '@/lib/images';

export const collections: Collection[] = [
  {
    id: 'zenana-edit',
    slug: 'zenana-edit',
    name: 'The Zenana Edit',
    description: 'Jewelry for the inner chambers — intimate pieces worn close to skin, passed between generations of women.',
    story: "In the zenana, the women's quarters of Rajput palaces, jewelry was not adornment but language. A choker whispered of a new bride's nervous heart. An anklet announced a queen's midnight walk to the temple. These pieces carry that vocabulary — each curve, each stone placement, a word in a dialect only women truly understand.",
    heroImage: img.zenanaHero,
    heroImageAlt: 'Model wearing Zenana Edit choker in warm directional light',
    thumbnailImage: img.zenanaThumb,
    order: 1,
    isActive: true,
    products: [],
  },
  {
    id: 'maharani-suite',
    slug: 'maharani-suite',
    name: 'The Maharani Suite',
    description: 'Ceremonial grandeur reimagined for the modern sovereign — statement pieces that command rooms without speaking.',
    story: "The maharani did not wear jewelry to be seen. She wore it to remember who she was. This suite draws from archival pieces in Jaipur's City Palace — sarpech turban ornaments transformed into brooches, haathphool reimagined as cuff bracelets. Grandeur stripped of ostentation.",
    heroImage: img.maharaniHero,
    heroImageAlt: 'Maharani Suite necklace on dark aubergine background',
    thumbnailImage: img.maharaniThumb,
    order: 2,
    isActive: true,
    products: [],
  },
  {
    id: 'artisan-line',
    slug: 'artisan-line',
    name: 'The Artisan Line',
    description: 'Daily companions — unadorned gold, hammered silver, raw stone. The quiet luxury of things made by hand.',
    story: "A karigar's hands know gold the way a potter knows clay. This line honors that intimacy — no casting molds, no machine finishes. Each piece bears the subtle irregularities of the hammer, the file, the burnisher. Wear them and you carry the maker's fingerprint.",
    heroImage: img.artisanHero,
    heroImageAlt: 'Hammered gold cuff from Artisan Line on linen',
    thumbnailImage: img.artisanThumb,
    order: 3,
    isActive: true,
    products: [],
  },
  {
    id: 'bridal-archive',
    slug: 'bridal-archive',
    name: 'The Bridal Archive',
    description: 'By appointment only. Heirloom sets crafted for the one day that becomes every day after.',
    story: "A bride's jewelry is her first inheritance to the next generation. We work with families six months before the wedding — understanding her, her mother, her grandmother's pieces. The result is not a set but a story: her nath reimagined, her grandmother's diamonds reset, a new choker designed to sit beside them all.",
    heroImage: img.bridalHero,
    heroImageAlt: 'Bridal Archive set displayed on raw silk',
    thumbnailImage: img.bridalThumb,
    order: 4,
    isActive: true,
    products: [],
  },
];

export const products: Product[] = [
  {
    id: 'zenana-choker',
    slug: 'zenana-choker',
    name: 'Zenana Choker',
    collectionId: 'zenana-edit',
    description: 'A collar of oxidized silver and uncut polki diamonds, designed to rest at the hollow of the throat.',
    story: "Inspired by the chokers worn by zenana attendants — close-fitting, secure, meant for days of service and nights of prayer. The polki diamonds catch candlelight the way they did in 18th century palaces. Oxidized silver grounds the brilliance, making it wearable with cotton as easily as silk.",
    price: 185000,
    currency: 'INR',
    metal: 'Oxidized Sterling Silver, 22K Gold Accents',
    stones: ['Uncut Polki Diamonds (3.2 carats total)', 'Natural Basra Pearls (4)'],
    weight: '42 grams',
    dimensions: '14" length, 1.2" max width',
    images: [
      { url: img.zenanaChokerHero, alt: 'Zenana Choker on model in warm light', type: 'hero', width: 1600, height: 2000 },
      { url: img.zenanaChokerDetail, alt: 'Macro detail of polki diamond setting', type: 'detail', width: 1600, height: 1600 },
      { url: img.zenanaChokerOnBody, alt: 'Zenana Choker worn with cotton kurta', type: 'on-body', width: 1600, height: 2000 },
      { url: img.zenanaChokerMacro, alt: 'Extreme close-up of hammered silver texture', type: 'macro', width: 1600, height: 1600 },
    ],
    isAvailable: true,
    isFeatured: true,
    makingOf: {
      title: 'The Making of the Zenana Choker',
      description: 'Each choker begins as a silver sheet, hand-hammered over a curved anvil to achieve its ergonomic collar shape. The polki diamonds are set using the traditional kundan technique — gold foil backing each stone to maximize its fire. The final oxidation is applied by hand, then selectively polished to reveal highlights.',
      image: img.zenanaChokerWorkshop,
      imageAlt: 'Karigar hammering silver choker form',
      steps: [
        { step: 1, title: 'Forming', description: 'Silver sheet hammered over curved anvil in 3 stages to achieve collar ergonomics.' },
        { step: 2, title: 'Setting', description: 'Polki diamonds set in kundan style — gold foil, lac, then bezel pushed by hand.' },
        { step: 3, title: 'Oxidation', description: 'Liver of sulfur patina applied, then selective burnishing for dimensional highlights.' },
        { step: 4, title: 'Pearls', description: 'Natural Basra pearls drilled and strung on silk, knotted between each.' },
      ],
    },
  },
  {
    id: 'maharani-necklace',
    slug: 'maharani-necklace',
    name: 'Maharani Necklace',
    collectionId: 'maharani-suite',
    description: 'Graduated emerald and diamond necklace with detachable pendant — wearable as choker or opera length.',
    story: "Commissioned by a Jaipur family for their daughter's wedding. The central emerald — a 12-carat Colombian stone — was sourced by her great-grandfather. We reset it with graduating old-cut diamonds and designed the chain to convert: wear it tight at the throat for evening, long over a silk kurta for day.",
    price: 4200000,
    currency: 'INR',
    metal: '22K Yellow Gold, Platinum Settings',
    stones: ['Colombian Emerald (12.4 carats)', 'Old European Cut Diamonds (8.6 carats total)', 'Natural Basra Pearls (12)'],
    weight: '86 grams',
    dimensions: '16"–28" adjustable, 2.4" pendant drop',
    images: [
      { url: img.maharaniNecklaceHero, alt: 'Maharani Necklace on velvet', type: 'hero', width: 1600, height: 2000 },
      { url: img.maharaniNecklaceDetail, alt: 'Emerald and diamond detail', type: 'detail', width: 1600, height: 1600 },
      { url: img.maharaniNecklaceOnBody, alt: 'Necklace worn as opera length', type: 'on-body', width: 1600, height: 2000 },
      { url: img.maharaniNecklaceMacro, alt: 'Macro of platinum prong work', type: 'macro', width: 1600, height: 1600 },
    ],
    isAvailable: true,
    isFeatured: true,
    makingOf: {
      title: 'The Making of the Maharani Necklace',
      description: 'A six-month collaboration between our head designer and the family. The emerald was recut to optimize its color — a decision made only after weeks of light-box study. The platinum settings for diamonds were fabricated separately, then married to the 22K gold chain using a technique that leaves no visible seam.',
      image: img.maharaniNecklaceWorkshop,
      imageAlt: 'Designer examining emerald under loupe',
      steps: [
        { step: 1, title: 'Stone Study', description: 'Emerald analyzed under polarized light; recut plan approved by family gemologist.' },
        { step: 2, title: 'Layout', description: 'Diamond graduation mapped on paper, then wax — each stone position numbered.' },
        { step: 3, title: 'Fabrication', description: 'Platinum settings cast, hand-finished. Gold chain links individually soldered.' },
        { step: 4, title: 'Assembly', description: 'Stones set over 40 hours. Chain converted with hidden sliding mechanism.' },
      ],
    },
  },
  {
    id: 'artisan-cuff',
    slug: 'artisan-cuff',
    name: 'Artisan Hammered Cuff',
    collectionId: 'artisan-line',
    description: 'Single-piece forged gold cuff, hand-hammered from ingot. No two identical.',
    story: "This is the piece our karigars make for themselves. Start with a 22K gold ingot. Heat, hammer, anneal, repeat — over three days the metal finds its form. The surface records every strike. No polishing to mirror finish; the matte gold catches light like brushed sandstone.",
    price: 340000,
    currency: 'INR',
    metal: '22K Yellow Gold (91.6% pure)',
    stones: [],
    weight: '58 grams',
    dimensions: '2.4" inner diameter, 4mm thickness, 8mm width',
    images: [
      { url: img.artisanCuffHero, alt: 'Hammered gold cuff on stone', type: 'hero', width: 1600, height: 1600 },
      { url: img.artisanCuffDetail, alt: 'Hammer texture macro', type: 'detail', width: 1600, height: 1600 },
      { url: img.artisanCuffOnBody, alt: 'Cuff worn with linen shirt', type: 'on-body', width: 1600, height: 1600 },
      { url: img.artisanCuffMacro, alt: 'Extreme close-up of hammer marks', type: 'macro', width: 1600, height: 1600 },
    ],
    isAvailable: true,
    isFeatured: true,
    makingOf: {
      title: 'The Making of the Artisan Cuff',
      description: 'No molds. No rolling mill. A single ingot transformed by hammer and anvil — the oldest goldsmithing technique, unchanged in 5,000 years. The karigar works by feel: the ring of the hammer, the resistance of the metal, the heat in his palm.',
      image: img.artisanCuffWorkshop,
      imageAlt: 'Karigar forging gold cuff on anvil',
      steps: [
        { step: 1, title: 'Ingot', description: '22K gold cast into rectangular ingot, weighed, hallmarked.' },
        { step: 2, title: 'Forging', description: 'Heated to cherry red, hammered into taper. Annealed. Repeated 40+ times.' },
        { step: 3, title: 'Shaping', description: 'Formed over mandrel to final diameter. Edges filed by hand.' },
        { step: 4, title: 'Finish', description: 'Wire brush texture. No polish. Hallmark stamped inside.' },
      ],
    },
  },
  {
    id: 'bridal-suite-complete',
    slug: 'bridal-suite-complete',
    name: 'Complete Bridal Suite',
    collectionId: 'bridal-archive',
    description: 'Choker, haathphool, earrings, maang tikka, nath, and waist chain — designed as a cohesive narrative.',
    story: "Designed for a bride who wore her grandmother's choker but wanted something new for her reception. We created a suite where each piece references the choker's motif — a stylized lotus — but in different metals and stones. The haathphool uses the same polki diamonds. The nath echoes the lotus in a single pearl. The waist chain is a quiet gold thread.",
    price: 2800000,
    currency: 'INR',
    metal: '22K Gold, Oxidized Silver, Platinum',
    stones: ['Polki Diamonds (18 carats total)', 'Emeralds (6 carats)', 'Basra Pearls (24)', 'Rubies (4 carats)'],
    weight: '280 grams total',
    dimensions: 'Custom fitted',
    images: [
      { url: img.bridalSuiteHero, alt: 'Full bridal suite on raw silk', type: 'hero', width: 1600, height: 2000 },
      { url: img.bridalSuiteDetail, alt: 'Detail of lotus motif across pieces', type: 'detail', width: 1600, height: 1600 },
      { url: img.bridalSuiteOnBody, alt: 'Bride wearing complete suite', type: 'on-body', width: 1600, height: 2000 },
      { url: img.bridalSuiteMacro, alt: 'Macro of polki setting', type: 'macro', width: 1600, height: 1600 },
    ],
    isAvailable: false,
    isFeatured: true,
    makingOf: {
      title: 'The Making of the Bridal Suite',
      description: 'Eight months from first meeting to wedding day. The grandmother\'s choker was documented, dismantled, stones reclaimed. New pieces designed around them. Three fittings with the bride. The waist chain length adjusted after her final lehenga fitting.',
      image: img.bridalSuiteWorkshop,
      imageAlt: 'Designer and bride at fitting',
      steps: [
        { step: 1, title: 'Archive', description: "Grandmother's pieces photographed, weighed, stones catalogued." },
        { step: 2, title: 'Design', description: 'Lotus motif developed across 6 pieces. Wax models 3D printed for approval.' },
        { step: 3, title: 'Fabrication', description: 'Reclaimed stones reset. New gold alloyed to match vintage tone.' },
        { step: 4, title: 'Fittings', description: 'Three sessions. Final adjustments made 48 hours before wedding.' },
      ],
    },
  },
];

export const journalArticles: JournalArticle[] = [
  {
    id: 'hands-that-make',
    slug: 'hands-that-make',
    title: 'The Hands That Make',
    dek: 'A portrait of Master Karigar Raghav-ji, 40 years at the bench, and the quiet language of hammer on gold.',
    heroImage: img.journalHandsHero,
    heroImageAlt: 'Raghav-ji at his bench, loupe on, hammer poised',
    author: 'Apriliha Singh',
    authorRole: 'Founder & Creative Director',
    publishedAt: '2025-01-15',
    readTime: 8,
    category: 'atelier',
    isFeatured: true,
    tags: ['craftsmanship', 'karigar', 'process', 'jaipur'],
    content: [
      { type: 'paragraph', content: "Raghav-ji does not speak much. He lets the metal speak for him. When a piece of gold resists the hammer — sings a different note — he pauses. Adjusts the angle. Strikes again. The sound changes. 'Now it listens,' he says." },
      { type: 'paragraph', content: "He has been at this bench since he was fourteen. His father placed a hammer in his hand and said, 'Gold has memory. Treat it with respect, and it will remember your touch.' Forty years later, his hands move with the certainty of someone who has made ten thousand decisions, one strike at a time." },
      { type: 'heading', content: 'The Language of Resistance', level: 2 },
      { type: 'paragraph', content: "Most people think goldsmithing is about force. It is not. It is about listening. The metal tells you when it is ready to move, when it needs fire, when it needs rest. A karigar who forces the metal creates stress fractures — invisible lines that become cracks years later. A karigar who listens creates pieces that last generations." },
      { type: 'image', image: img.journalHandsHammer, imageAlt: 'Close-up of hammer striking gold', caption: 'The hammer Raghav-ji has used for 22 years. Its face is polished by thousands of strikes.' },
      { type: 'paragraph', content: "We watched him make a simple gold band. Three hours. No magnification for the first two — just his eyes, his fingers, the sound. Only for the final filing did he reach for his loupe. 'The loupe is for checking,' he said. 'The hands are for knowing.'" },
      { type: 'pull-quote', content: '"The loupe is for checking. The hands are for knowing."', alignment: 'center' },
      { type: 'heading', content: 'Apprenticeship in the Modern Age', level: 2 },
      { type: 'paragraph', content: "Raghav-ji has three apprentices now. They are 19, 21, and 24. They came to him after engineering degrees, disillusioned by screens. The first year, they do not touch gold. They sweep. They fetch tea. They watch. 'You learn with your eyes before your hands,' he tells them. 'If you cannot see the grain in the metal, you have no business striking it.'" },
      { type: 'image', image: img.journalApprentices, imageAlt: 'Three apprentices watching Raghav-ji work', caption: 'First-year apprentices. They will not touch gold for twelve months.' },
      { type: 'paragraph', content: "The 24-year-old, Arjun, showed us his first piece — a simple wire ring, made last week. 'It took me six hours,' he said, a rare smile. 'Raghav-ji makes it in forty minutes. But he said my hammer strikes were clean. That was the best moment of my life.'" },
      { type: 'heading', content: 'What We Owe Them', level: 2 },
      { type: 'paragraph', content: "Every piece that leaves our atelier carries Raghav-ji's touch — either directly, or through the hands he has trained. His standards are our standards. His patience is our timeline. His respect for the material is our philosophy." },
      { type: 'paragraph', content: "When you wear an Apriliha Singh piece, you are not wearing a product. You are wearing forty years of listening to gold. You are wearing the hands that know." },
      { type: 'divider' },
      { type: 'paragraph', content: "This article is part of our ongoing series documenting the karigars of our atelier. Next month: the stone-setter who places each diamond by feel alone." },
    ],
  },
  {
    id: 'stone-speaks',
    slug: 'stone-speaks',
    title: 'When the Stone Speaks',
    dek: 'How we select, cut, and set gemstones — and why the stone always has the final word.',
    heroImage: img.journalStoneHero,
    heroImageAlt: 'Rough emerald crystals on dark velvet',
    author: 'Priya Mehta',
    authorRole: 'Head of Gemstone Sourcing',
    publishedAt: '2024-11-22',
    readTime: 6,
    category: 'craft',
    isFeatured: false,
    tags: ['gemstones', 'sourcing', 'ethics', 'cutting'],
    content: [
      { type: 'paragraph', content: "A rough emerald sits on my desk. Twelve carats. Colombian. Included — jardin, the French call it, garden. To the untrained eye, flaws. To me, a map." },
      { type: 'paragraph', content: "I have spent twenty years learning to read these maps. Each inclusion tells a story of the earth's pressure, the heat, the time. The cutter's job is not to remove them all — that would waste the stone. It is to orient the cut so the inclusions become part of the beauty, like branches in a winter sky." },
      { type: 'heading', content: 'The Ethics of Origin', level: 2 },
      { type: 'paragraph', content: "We trace every stone. Colombian emeralds from Muzo, where we know the mine owners by name. Basra pearls from the Persian Gulf, harvested by divers whose families have done this for generations. Golconda diamonds — when we can find them — from estates, not new mining." },
      { type: 'image', image: img.journalGemstoneSelection, imageAlt: 'Gemstones being examined under light', caption: 'Selection day. Only 1 in 20 rough stones meets our standards.' },
      { type: 'paragraph', content: "We do not buy from dealers who cannot tell us the mine. We do not buy calibrated stones — mass-produced, identical, soulless. Every stone in our jewelry was chosen by hand, for that specific piece." },
      { type: 'heading', content: 'The Cutting Decision', level: 2 },
      { type: 'paragraph', content: "Last month, a 15-carat Kashmir sapphire. The cutter wanted to maximize weight — oval cut, 12 carats finished. I said no. The color zoning demanded a cushion cut, 9 carats, but the blue would be electric. We lost 6 carats. We gained a stone that stops breath." },
      { type: 'pull-quote', content: '"We lost 6 carats. We gained a stone that stops breath."', alignment: 'center' },
      { type: 'paragraph', content: "That is the calculus. Not carat weight. Not certificate grades. The moment the stone catches light and holds it — that is the only metric that matters." },
    ],
  },
  {
    id: 'jaipur-monsoon',
    slug: 'jaipur-monsoon',
    title: 'Jaipur in Monsoon',
    dek: 'The city transforms. The dust settles. The stones drink the rain. A photo essay.',
    heroImage: img.journalMonsoonHero,
    heroImageAlt: 'Jaipur palace reflected in monsoon water',
    author: 'Rohit Sharma',
    authorRole: 'Documentary Photographer',
    publishedAt: '2024-08-10',
    readTime: 4,
    category: 'stories',
    isFeatured: false,
    tags: ['jaipur', 'photography', 'monsoon', 'atmosphere'],
    content: [
      { type: 'paragraph', content: "The first rain hits the pink sandstone and the city exhales. Three months of 45-degree heat broken in twenty minutes. The dust — that constant Jaipur companion — surrenders to gravity." },
      { type: 'image', image: img.journalMonsoon1, imageAlt: 'Rain on palace facade', caption: 'City Palace walls, washed clean after months of dust.' },
      { type: 'paragraph', content: "In the workshop, the karigars open the jali windows. The humid air is good for gold — less static, easier to work. They say the metal 'breathes' in monsoon. I watch Raghav-ji pause, smell the petrichor rising from the courtyard, then return to his hammer." },
      { type: 'image', image: img.journalMonsoon2, imageAlt: 'Workshop window with rain', caption: "The atelier's jali window. Same view for three generations." },
      { type: 'paragraph', content: "The stones change too. Opals drink the humidity, their fire deepening. Pearls, born of water, seem to remember their origin. Even diamonds — cold, indifferent — catch the monsoon light differently, scattered through rain-washed air." },
      { type: 'image', image: img.journalMonsoon3, imageAlt: 'Gemstones on wet stone', caption: 'Stones on the testing plate. Monsoon light reveals colors indoor lamps miss.' },
      { type: 'paragraph', content: "This is why we are here. Not in Mumbai, not in Delhi. Jaipur's rhythm is in our jewelry. The heat, the dust, the monsoon, the winter mornings when the marble is cold against bare feet. Every piece carries this place." },
    ],
  },
];

export const atelierContent = {
  founderStory: {
    portrait: img.founderPortrait,
    portraitAlt: 'Apriliha Singh in the atelier',
    name: 'Apriliha Singh',
    title: 'Founder & Creative Director',
    pullQuote: '"We work the way Jaipur\'s karigars have for generations — by hand, by hammer, by patience. What\'s modern is everything else."',
    biography: [
      'Born in Jaipur, raised between the City Palace archives and her grandmother\'s jewelry box. Apriliha studied design at NID Ahmedabad, then spent three years at a Parisian haute joaillerie house before returning home with a singular vision: to build a house that honors Indian craftsmanship without exoticizing it.',
      'She does not design collections. She designs conversations — between karigar and client, between tradition and now, between the stone and the hand that sets it. Every piece begins as a dialogue in the workshop, not a sketch on a screen.',
      'Under her direction, the atelier has revived three near-lost techniques: kundan setting without shellac, granulation in 22K gold, and the art of the invisible hinge. Her work has been exhibited at the V&A Museum\'s "India Modern" show and acquired by the Metropolitan Museum of Art\'s permanent collection.',
    ],
  },
  craftProcess: [
    {
      step: 1,
      title: 'Sketch & Dialogue',
      description: 'No CAD. No 3D renders. Every piece begins as a conversation between Apriliha and the head karigar, drawn in charcoal on handmade paper. The drawing evolves over days — sometimes weeks — as the metal\'s possibilities are discussed.',
      image: img.processSketch,
      imageAlt: 'Charcoal sketch on handmade paper with annotations',
    },
    {
      step: 2,
      title: 'Wax Carving',
      description: 'The approved sketch becomes a wax model, carved by hand using dental tools and heated spatulas. This is where proportions are resolved — the weight distribution, the way a necklace will fall, the angle of a stone setting. The wax is tried on, adjusted, re-carved.',
      image: img.processWax,
      imageAlt: 'Karigar carving wax model',
    },
    {
      step: 3,
      title: 'Lost-Wax Casting',
      description: 'The wax is invested in plaster, burned out in a clay kiln, and molten gold poured into the void. This ancient technique — unchanged since the Indus Valley — captures every fingerprint of the wax carving. The raw casting emerges rough, perfect in its imperfection.',
      image: img.processCast,
      imageAlt: 'Raw gold casting just out of plaster',
    },
    {
      step: 4,
      title: 'Hand Finishing',
      description: 'Files, scrapers, burnishers. The karigar spends days — sometimes weeks — refining every surface. Internal curves polished to silk. External surfaces left with intentional texture: hammered, brushed, matte. No machine polishing. The hand knows where the light will fall.',
      image: img.processFinish,
      imageAlt: 'Karigar hand-finishing a gold piece',
    },
    {
      step: 5,
      title: 'Stone Setting',
      description: 'Each stone is set by a specialist. Kundan for polki — gold foil, lac, bezel pushed by thumb. Prong for faceted stones — platinum claws fabricated per stone. Bead for pave — microscopic grains of gold raised and burnished. No glue. Ever.',
      image: img.processSet,
      imageAlt: 'Stone setter at work under loupe',
    },
    {
      step: 6,
      title: 'Final Assembly & Blessing',
      description: 'Components united. Clasps tested fifty times. Chains checked link by link. The piece rests for 24 hours — gold settles. Then a quiet moment: the head karigar places a pinch of turmeric at the clasp, a tradition from his guru. The piece is ready.',
      image: img.processFinal,
      imageAlt: 'Completed piece on velvet with turmeric blessing',
    },
  ],
  materials: {
    gold: {
      origin: 'Single-source 22K from a family-run refinery in Jaipur\'s Johari Bazaar, operating since 1847. We know the mine, the smelter, the alloy master.',
      description: 'We use 22K (91.6% pure) almost exclusively — the traditional alloy of Indian jewelry. Its warmth, its weight, its workability under the hammer — 18K cannot replicate it. For structural elements requiring spring tension (clasps, hinges), we use 18K or platinum.',
      image: img.goldIngots,
      imageAlt: '22K gold ingots with hallmark stamps',
    },
    stones: {
      origin: 'Colombian emeralds (Muzo, Chivor), Kashmir sapphires (estate only), Golconda diamonds (estate only), Basra pearls (Persian Gulf), Burmese rubies (Mogok, pre-2008 stock). Every stone traceable to source.',
      description: 'We do not buy calibrated stones. Each gem is selected for a specific piece — its color, its inclusions, its personality. We work with three cutter families in Jaipur and Bangkok who cut exclusively for us. The stone dictates the cut, not the market.',
      image: img.stoneSelection,
      imageAlt: 'Gemstones being selected under daylight lamp',
    },
    ethics: 'We are members of the Responsible Jewellery Council. Our gold is recycled or single-source traceable. Our stones are conflict-free by origin, not just certificate. We pay our karigars 3x the Jaipur workshop average, with health insurance, pension, and profit-sharing. The atelier runs on 60% solar. Our packaging is handmade khaddi paper boxes, reusable as jewelry storage.',
  },
  workshopGallery: [
    { url: img.gallery1, alt: 'Karigar at bench with morning light', caption: 'Morning light through the jali. The best setting light.' },
    { url: img.gallery2, alt: 'Wall of handmade tools', caption: 'Each karigar makes their own tools. This wall represents 150 years of accumulated knowledge.' },
    { url: img.gallery3, alt: 'Gold dust being collected', caption: 'Nothing wasted. Gold dust swept, melted, reborn.' },
    { url: img.gallery4, alt: 'Apprentice learning file work', caption: 'First year: file work. The foundation of all finishing.' },
    { url: img.gallery5, alt: 'Kiln for lost-wax casting', caption: 'Clay kiln, wood-fired. The temperature judged by flame color.' },
    { url: img.gallery6, alt: 'Finished pieces awaiting blessing', caption: 'Ready for the turmeric touch. Then to their new homes.' },
  ],
};

export const socialLinks: SocialLink[] = [
  { platform: 'instagram', url: 'https://instagram.com/aprilihasingh', label: 'Instagram' },
  { platform: 'pinterest', url: 'https://pinterest.com/aprilihasingh', label: 'Pinterest' },
  { platform: 'email', url: 'mailto:concierge@aprilihasingh.com', label: 'Email' },
  { platform: 'whatsapp', url: 'https://wa.me/919876543210', label: 'WhatsApp' },
];

export const footerColumns: FooterColumn[] = [
  {
    heading: 'Shop',
    links: [
      { label: 'Collections', href: '/collections' },
      { label: 'The Zenana Edit', href: '/collections/zenana-edit' },
      { label: 'The Maharani Suite', href: '/collections/maharani-suite' },
      { label: 'The Artisan Line', href: '/collections/artisan-line' },
      { label: 'Bridal Archive', href: '/collections/bridal-archive' },
    ],
  },
  {
    heading: 'About',
    links: [
      { label: 'The Atelier', href: '/atelier' },
      { label: 'Our Karigars', href: '/atelier#karigars' },
      { label: 'Materials & Ethics', href: '/atelier#materials' },
      { label: 'Journal', href: '/journal' },
    ],
  },
  {
    heading: 'Client Care',
    links: [
      { label: 'Book Appointment', href: '/appointment' },
      { label: 'Bespoke Commissions', href: '/appointment#bespoke' },
      { label: 'Care Guide', href: '/care-guide' },
      { label: 'Shipping & Returns', href: '/shipping-returns' },
      { label: 'Repair & Restoration', href: '/repair' },
    ],
  },
  {
    heading: 'Contact',
    links: [
      { label: 'Concierge', href: '/contact' },
      { label: 'Press Inquiries', href: '/contact#press' },
      { label: 'WhatsApp: +91 98765 43210', href: 'https://wa.me/919876543210' },
      { label: 'Email: concierge@aprilihasingh.com', href: 'mailto:concierge@aprilihasingh.com' },
      { label: 'Jaipur Atelier (By Appt.)', href: '/contact#visit' },
    ],
  },
];

export const navItems = [
  { label: 'Collections', href: '/collections' },
  { label: 'The Atelier', href: '/atelier' },
  { label: 'Journal', href: '/journal' },
  { label: 'Book an Appointment', href: '/appointment' },
];

export const heroSlides: HeroSlide[] = [
  {
    id: 'hero-1',
    title: 'Jewelry for life, not just occasions.',
    image: img.homeHero,
    imageAlt: 'Apriliha Singh atelier interior with warm directional light',
    href: '/collections',
  },
  {
    id: 'hero-2',
    title: 'The Zenana Edit',
    image: img.zenanaHero,
    imageAlt: 'The Zenana Edit collection',
    href: '/collections/zenana-edit',
  },
  {
    id: 'hero-3',
    title: 'The Maharani Suite',
    image: img.maharaniHero,
    imageAlt: 'The Maharani Suite collection',
    href: '/collections/maharani-suite',
  },
  {
    id: 'hero-4',
    title: 'Design Your Own',
    image: img.artisanHero,
    imageAlt: 'Bespoke jewelry design',
    href: '/design-your-own',
  },
  {
    id: 'hero-5',
    title: 'The Atelier',
    image: img.atelierPreview,
    imageAlt: 'Apriliha Singh atelier',
    href: '/atelier',
  },
];

export const projects: Project[] = [
  {
    id: 'bespoke-studio',
    title: 'Bespoke Studio',
    description: 'A mobile atelier experience bringing the craft of Jaipur to private appointments worldwide.',
    image: img.atelierPreview,
    imageAlt: 'Bespoke studio project',
    href: '/design-your-own',
  },
  {
    id: 'bridal-archive',
    title: 'The Bridal Archive',
    description: 'Heirloom sets crafted for the one day that becomes every day after.',
    image: img.bridalHero,
    imageAlt: 'Bridal Archive project',
    href: '/collections/bridal-archive',
  },
  {
    id: 'karigar-residency',
    title: 'Karigar Residency',
    description: 'Documenting three generations of hands at the bench in Jaipur.',
    image: img.journalHandsHero,
    imageAlt: 'Karigar residency project',
    href: '/journal/hands-that-make',
  },
];

export const storeLocations: StoreLocation[] = [
  {
    id: 'jaipur-atelier',
    name: 'JAIPUR',
    image: img.atelierPreview,
    imageAlt: 'Apriliha Singh Jaipur Atelier',
    href: '/appointment',
  },
  {
    id: 'studio-visit',
    name: 'STUDIO',
    image: img.homeHero,
    imageAlt: 'Apriliha Singh studio',
    href: '/appointment',
  },
  {
    id: 'private-viewing',
    name: 'PRIVATE VIEWING',
    image: img.zenanaThumb,
    imageAlt: 'Private viewing appointment',
    href: '/contact',
  },
];